//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamFinal_Ferreteria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbExamFinal_FerreteriaEntities : DbContext
    {
        public dbExamFinal_FerreteriaEntities()
            : base("name=dbExamFinal_FerreteriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Inventario> Tb_Inventario { get; set; }
        public virtual DbSet<Tb_Proveedor> Tb_Proveedor { get; set; }
    }
}
