//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamFinal_Ferreteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Inventario
    {
        public int idNoProducto { get; set; }
        public int Código_de_Producto { get; set; }
        public string Tipo_De_Producto { get; set; }
        public string Producto { get; set; }
        public Nullable<int> Existencias { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public decimal Precio_Público { get; set; }
        public Nullable<System.DateTime> Fecha_de_Ingreso { get; set; }
    }
}
