//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamFinal_Ferreteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proveedor
    {
        public int IdNoProveedor { get; set; }
        public string CodigoProveedor { get; set; }
        public string NombreEmpresaProveedora { get; set; }
        public string TipoProveedor { get; set; }
        public string Nombre { get; set; }
        public string DirecciónEmpresaSede { get; set; }
        public string Telefono1 { get; set; }
        public string telefonoEmpresa { get; set; }
        public string CorreoProveedor { get; set; }
        public string CorreoEmpresa { get; set; }
    }
}
